#################################################################
# WARNING: AUTO-GENERATED FILE - EDITS WILL BE OVERWRITTEN
# To make changes, edit the source .conf files in src/ directory
# Generator located tools/30_consolidate_module.sh
#################################################################
######## start core_options ########
#
declare -A core_options

core_options[yes_no_box,require_os]="Armbian Debian Ubuntu"
core_options[yes_no_box,contributor]="@tearran"
core_options[yes_no_box,group]="interface"
core_options[yes_no_box,options]="<message>"
core_options[yes_no_box,extend_desc]="The yes_no_box helper provides a consistent, script-friendly way to prompt users for Yes/No confirmations across different environ"
core_options[yes_no_box,documents]="true"
core_options[yes_no_box,port]="false"
core_options[yes_no_box,description]="Portable Bash yes/no prompt function supporting whiptail, dialog, or simple shell read fallback."
core_options[yes_no_box,require_kernel]="5.15+"
core_options[yes_no_box,maintainer]="true"
core_options[yes_no_box,helpers]="_about_yes_no_box"
core_options[yes_no_box,unique_id]="COR001"
core_options[yes_no_box,arch]="arm64 armhf x86-64"
core_options[yes_no_box,parent]="core"
core_options[yes_no_box,feature]="yes_no_box"
core_options[info_box,require_os]="Debian Ubuntu Armbian"
core_options[info_box,contributor]="@tearran"
core_options[info_box,group]="interface"
core_options[info_box,options]="[message] | (via stdin/pipe)"
core_options[info_box,extend_desc]="This helper provides a live-updating infobox for progress or log output in TUI (dialog/whiptail). When piped, shows the last N lines as they arrive. If called with an argument, displays it as a static message. Useful for monitoring, user feedback, or background task reporting in config-v3."
core_options[info_box,documents]="true"
core_options[info_box,port]="false"
core_options[info_box,description]="Display a rolling info box with dialog/whiptail; reads and shows lines from stdin or a single message."
core_options[info_box,require_kernel]="5.15+"
core_options[info_box,maintainer]="true"
core_options[info_box,helpers]="_about_info_box"
core_options[info_box,unique_id]="COR002"
core_options[info_box,arch]="arm64 armhf x86-64"
core_options[info_box,parent]="core"
core_options[info_box,feature]="info_box"
core_options[ok_box,require_os]="Armbian Debian Ubuntu"
core_options[ok_box,contributor]="@tearran"
core_options[ok_box,group]="interface"
core_options[ok_box,extend_disc]="Reads input text (either from standard input or as an argument) and presents it to the user with the selected dialog frontend. Supports dialog, whiptail, or plain read/echo. Handles input flexibly and routes output appropriately depending on the tool."
core_options[ok_box,options]="<message>"
core_options[ok_box,documents]="yes"
core_options[ok_box,port]="false"
core_options[ok_box,description]="Displays a message to the user using the configured dialog tool."
core_options[ok_box,require_kernel]="5.15+"
core_options[ok_box,maintainer]="false"
core_options[ok_box,helpers]="_about_ok_box"
core_options[ok_box,unique_id]="COR003"
core_options[ok_box,arch]="arm64 armhf x86-64"
core_options[ok_box,parent]="core"
core_options[ok_box,feature]="ok_box"
core_options[input_box,require_os]="Debian Ubuntu Armbian"
core_options[input_box,contributor]="@tearran"
core_options[input_box,group]="interface"
core_options[input_box,options]="["prompt"] or echo "prompt"  or <<< "prompt""
core_options[input_box,extend_desc]="This helper displays an input box for user input in TUI environments using dialog, whiptail, or a shell fallback. The prompt message can be supplied as a positional argument or piped via stdin. If no prompt is provided, usage help is shown. Supports ARM and x86-64 architectures on Debian, Ubuntu, and Armbian systems (kernel 5.15+). Useful for scripts needing interactive input with fallback and help options."
core_options[input_box,documents]="true"
core_options[input_box,port]="false"
core_options[input_box,description]="Prompt the user for input using whiptail, dialog, or shell fallback; reads prompt from argument or stdin and prints result to stdout."
core_options[input_box,require_kernel]="5.15+"
core_options[input_box,maintainer]="true"
core_options[input_box,helpers]="_about_input_box"
core_options[input_box,unique_id]="COR004"
core_options[input_box,arch]="arm64 armhf x86-64"
core_options[input_box,parent]="core"
core_options[input_box,feature]="input_box"
core_options[submenu,require_os]="Armbian Debian Ubuntu"
core_options[submenu,contributor]="@tearran"
core_options[submenu,group]="interface"
core_options[submenu,options]="<module_name help>"
core_options[submenu,extend_desc]="Parses the help message of a given module and presents an interactive menu via dialog, whiptail, or CLI prompt."
core_options[submenu,documents]="false"
core_options[submenu,port]="false"
core_options[submenu,description]="Displays an interactive submenu for module functions based on their help output."
core_options[submenu,require_kernel]="5.15+"
core_options[submenu,maintainer]="false"
core_options[submenu,helpers]="_about_submenu"
core_options[submenu,unique_id]="COR005"
core_options[submenu,arch]="arm64 armhf x86-64"
core_options[submenu,parent]="core"
core_options[submenu,feature]="submenu"
core_options[service,require_os]="Armbian Debian Ubuntu"
core_options[service,contributor]="@dimitry-ishenko"
core_options[service,group]="software"
core_options[service,options]="active daemon-reload disable enable enabled mask reload restart start status stop unmask"
core_options[service,extend_desc]="Helpers for managing services programmatically via systemd. Intended for use by configng-v2 core logic and scripts."
core_options[service,documents]="true"
core_options[service,port]="false"
core_options[service,description]="Systemd service management helpers (start  stop  enable  etc.)"
core_options[service,require_kernel]="5.15+"
core_options[service,maintainer]="false"
core_options[service,helpers]="_about_service srv_active srv_start srv_stop srv_restart srv_reload srv_status srv_enable srv_disable srv_enabled srv_mask srv_unmask srv_daemon_reload"
core_options[service,unique_id]="COR006"
core_options[service,arch]="arm64 armhf x86-64"
core_options[service,parent]="core"
core_options[service,feature]="service"
core_options[package,require_os]="Armbian Debian Ubuntu"
core_options[package,contributor]="@dimitry-ishenko"
core_options[package,group]="software"
core_options[package,options]="update upgrade full-upgrade install remove configure installed"
core_options[package,extend_desc]="Provides helpers for managing multiple package at once via apt and dpkg. Intended for use by configng-v2 core logic and scripts."
core_options[package,documents]="true"
core_options[package,port]="false"
core_options[package,description]="Helpers for bulk packages operations (install, remove, upgrade, etc.)"
core_options[package,require_kernel]="5.15+"
core_options[package,maintainer]="false"
core_options[package,helpers]="pkg_update pkg_upgrade pkg_full_upgrade pkg_install pkg_remove pkg_configure pkg_installed _about_package"
core_options[package,unique_id]="COR007"
core_options[package,arch]="arm64 armhf x86-64"
core_options[package,parent]="core"
core_options[package,feature]="package"
core_options[list_options,require_os]="Armbian Debian Ubuntu"
core_options[list_options,contributor]="@tearran"
core_options[list_options,group]="initialize"
core_options[list_options,options]="main core system software network help"
core_options[list_options,extend_desc]="Lists features/options for core, system, network, and software modules. Outputs usage and example commands for each group."
core_options[list_options,documents]="true"
core_options[list_options,port]="false"
core_options[list_options,description]="Show available option groups and their usage for configng-v2 modules."
core_options[list_options,require_kernel]="5.15+"
core_options[list_options,maintainer]="false"
core_options[list_options,helpers]="_about_list_options _merge_list_options _parse_list_options"
core_options[list_options,unique_id]="COR008"
core_options[list_options,arch]="arm64 armhf x86-64"
core_options[list_options,parent]="core"
core_options[list_options,feature]="list_options"
core_options[trace,require_os]="Debian Ubuntu Armbian"
core_options[trace,contributor]="@tearran"
core_options[trace,group]="initialize"
core_options[trace,options]="help trace reset total"
core_options[trace,extend_desc]="Provides timing, traceging, and progress utilities for Bash modules. Supports trace timing, and elapsed time reporting for module development and diagnostics."
core_options[trace,documents]="true"
core_options[trace,port]="false"
core_options[trace,description]="Lightweight timing and trace message for Armbian Config V3 modules."
core_options[trace,require_kernel]="5.15+"
core_options[trace,maintainer]="true"
core_options[trace,helpers]="_about_trace"
core_options[trace,unique_id]="COR009"
core_options[trace,arch]="arm64 armhf x86-64"
core_options[trace,parent]="core"
core_options[trace,feature]="trace"
#
######## finish core_options ########

######## start network_options ########
#
declare -A network_options

network_options[network_manager,require_os]="Armbian Debian Ubuntu"
network_options[network_manager,contributor]="@tearran"
network_options[network_manager,group]="interface"
network_options[network_manager,options]="NetworkManager networkd status help"
network_options[network_manager,extend_desc]="Provides a simple interface to toggle or display the Netplan network renderer. Does not manage service installation or enablement."
network_options[network_manager,documents]="true"
network_options[network_manager,port]="false"
network_options[network_manager,description]="Minimal Netplan renderer switcher for configng-v2. Set or check the current Netplan 'renderer' (NetworkManager or networkd) for all interfaces."
network_options[network_manager,require_kernel]="5.15+"
network_options[network_manager,maintainer]="false"
network_options[network_manager,helpers]="_about_network_manager"
network_options[network_manager,unique_id]="NET001"
network_options[network_manager,arch]="arm64 armhf x86-64"
network_options[network_manager,parent]="network"
network_options[network_manager,feature]="network_manager"
#
######## finish network_options ########

######## start software_options ########
#
declare -A software_options

software_options[samba,require_os]="Armbian Debian Ubuntu"
software_options[samba,contributor]="@Tearran"
software_options[samba,group]="transfer"
software_options[samba,options]="install remove start stop enable disable configure default status"
software_options[samba,extend_desc]="Module for managing Samba service, installation, and configuration."
software_options[samba,documents]="true"
software_options[samba,port]="445"
software_options[samba,description]="Samba setup and service settings."
software_options[samba,require_kernel]="5.15+"
software_options[samba,maintainer]="true"
software_options[samba,helpers]="_about_samba"
software_options[samba,unique_id]="SOF001"
software_options[samba,arch]="arm64 armhf x86-64"
software_options[samba,parent]="software"
software_options[samba,feature]="samba"
software_options[cockpit,require_os]="Armbian Debian Ubuntu"
software_options[cockpit,contributor]="@tearran"
software_options[cockpit,group]="user"
software_options[cockpit,options]="install remove start stop status enable disable help"
software_options[cockpit,extend_desc]="Cockpit provides an easy-to-use, web-based graphical interface for system administration tasks such as managing users, services, storage, networking, and system updates. This module integrates Cockpit with Armbian Config V3, allowing users to install, remove, enable, disable, start, stop, and check the status of Cockpit directly from the config-ng menu or CLI."
software_options[cockpit,documents]="true"
software_options[cockpit,port]="false"
software_options[cockpit,description]="Web-based administrative interface for managing Linux servers."
software_options[cockpit,require_kernel]="5.15+"
software_options[cockpit,maintainer]="false"
software_options[cockpit,helpers]="_about_cockpit"
software_options[cockpit,unique_id]="SOF002"
software_options[cockpit,arch]="arm64 armhf x86-64"
software_options[cockpit,parent]="software"
software_options[cockpit,feature]="cockpit"
#
######## finish software_options ########

######## start system_options ########
#
declare -A system_options

system_options[adjust_motd,require_os]="Armbian Debian Ubuntu"
system_options[adjust_motd,contributor]="@igorpecovnik"
system_options[adjust_motd,group]="login"
system_options[adjust_motd,options]="show,set <item> <ON|OFF>,reload,help"
system_options[adjust_motd,documents]="true"
system_options[adjust_motd,port]="false"
system_options[adjust_motd,description]="Adjust welcome screen (motd)"
system_options[adjust_motd,require_kernel]="5.15+"
system_options[adjust_motd,maintainer]="true"
system_options[adjust_motd,helpers]="_about_adjust_motd _set_adjust_motd  _reload_adjust_motd"
system_options[adjust_motd,unique_id]="SYS001"
system_options[adjust_motd,arch]="arm64 armhf x86-64"
system_options[adjust_motd,parent]="system"
system_options[adjust_motd,feature]="adjust_motd"
#
######## finish system_options ########

