#!/usr/bin/env bash
set -euo pipefail

# ./software.sh - Armbian Config V2 module

# src/modules.d/software.sh

# ----------------------------------------------------------------------
# DO NOT EDIT THIS FILE DIRECTLY.
# This file may be generated by a flattening or build process.
# Edit the source modules instead.
#
# Duplicate functions may exist by design.
# ----------------------------------------------------------------------

software() {
	case "${1:-help}" in
		help|-h|--help)
			_about_software
			;;
		*)
			_about_software
			;;
	esac
}

_about_software() {
	cat <<-EOF
	Usage: software <command>
	Manage software-related features and modules.

	Commands:
	  help        Show this help message

	Examples:
	  software help

	Notes:
	  - Add more commands by extending the case block in software().
	  - Each command should have its own function and documentation.
	EOF
}

# ./software.sh - Armbian Config V2 test entrypoint

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
	software "${@:-help}"
fi

