review:
  waitForChecks: true
  path_instructions:
    - path: "src/**/*.sh"
      instructions: |
        Shell script review:
        - Proper variable quoting
        - Portable shell features
        - Security considerations
        - Error handling patterns
