name: "Check staging/ has any files"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'staging/**'
      - '.github/workflows/check-staging-any-file.yml'

jobs:
  check-staging-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if staging/ has any files
        run: |
          if [ "$(ls -A staging 2>/dev/null)" ]; then
            echo "staging/ is not empty."
          else
            echo "ERROR: staging/ is empty."
            exit 1
          fi