name: Check .sh and .meta file pairs

on:
  push:
    paths:
      - '*.sh'
      - '*.meta'
  pull_request:
    paths:
      - '*.sh'
      - '*.meta'

jobs:
  check-meta-sh-pairs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for matching .sh and .meta files
        run: |
          set -e
          shopt -s nullglob
          sh_files=(*.sh)
          meta_files=(*.meta)
          fail=0

          # Check that every .sh has a matching .meta
          for sh in "${sh_files[@]}"; do
            root="${sh%.sh}"
            if [[ ! -f "$root.meta" ]]; then
              echo "No matching .meta file for $sh"
              fail=1
            fi
          done

          # Check that every .meta has a matching .sh
          for meta in "${meta_files[@]}"; do
            root="${meta%.meta}"
            if [[ ! -f "$root.sh" ]]; then
              echo "No matching .sh file for $meta"
              fail=1
            fi
          done

          if [[ $fail -eq 1 ]]; then
            echo "One or more .sh/.meta file pairs are missing!"
            exit 1
          fi

          echo "All .sh and .meta files have matching root names."