name: Staging Gate

on:
  pull_request:
    paths:
      - 'staging/**'
      - 'tools/staging_check_required.sh'

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fail if staging folder is missing or empty
        run: |
          if [ ! -d staging ] || [ -z "$(ls -A staging)" ]; then
          	echo "::error ::staging folder is missing or empty. Please add or update at least one module."
          	exit 1
          fi

      - name: Staging compatibility check
        run: |
          chmod +x tools/staging_check_required.sh
          tools/staging_check_required.sh