name: Style and CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

concurrency:
  group: staging-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run style checks
        run: ./scripts/check_style.sh

  test:
    needs: style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: ./scripts/run_tests.sh

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy
        run: ./scripts/deploy.sh