name: 00 Staging Check

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, review_requested]

concurrency:
  group: coding-style-${{github.event.pull_request.number}}
  cancel-in-progress: true

jobs:
  staging-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run staging required check
        run: bash tools/staging_check_required.sh