name: "Check ./staging/ has matching .sh and .meta files on PR"

on:
  pull_request:
    paths:
      - 'staging/**'
      - '.github/workflows/check-staging-matching-files.yml'

jobs:
  check-matching-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for matching .sh and .meta files in ./staging/
        run: |
          cd staging

          # List all base names for .sh and .meta files
          sh_files=$(find . -maxdepth 1 -type f -name "*.sh" | sed 's|^\./||' | sed 's|\.sh$||' | sort)
          meta_files=$(find . -maxdepth 1 -type f -name "*.meta" | sed 's|^\./||' | sed 's|\.meta$||' | sort)

          # Check for unmatched .sh files
          missing_meta=$(comm -23 <(echo "$sh_files") <(echo "$meta_files"))
          # Check for unmatched .meta files
          missing_sh=$(comm -13 <(echo "$sh_files") <(echo "$meta_files"))

          error=0

          if [ -n "$missing_meta" ]; then
            echo "ERROR: The following .sh files do not have matching .meta files:"
            echo "$missing_meta"
            error=1
          fi

          if [ -n "$missing_sh" ]; then
            echo "ERROR: The following .meta files do not have matching .sh files:"
            echo "$missing_sh"
            error=1
          fi

          if [ $error -ne 0 ]; then
            echo ""
            echo "To create or fix the scaffold in ./staging, run:"
            echo "    tools/staging_setup_scaffold.sh"
            echo ""
            exit 1
          else
            echo "All .sh files have matching .meta files and vice versa."
          fi