name: Check .sh and .meta file pairs

on:
  pull_request:
    paths:
      - '*.sh'
      - '*.meta'

jobs:
  check-pairs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check .sh/.meta pairs
        run: |
          set -e
          shopt -s nullglob
          sh_files=(*.sh)
          meta_files=(*.meta)
          fail=0

          for sh in "${sh_files[@]}"; do
            root="${sh%.sh}"
            if [[ ! -f "$root.meta" ]]; then
              echo "No matching .meta file for $sh"
              fail=1
            fi
          done

          for meta in "${meta_files[@]}"; do
            root="${meta%.meta}"
            if [[ ! -f "$root.sh" ]]; then
              echo "No matching .sh file for $meta"
              fail=1
            fi
          done

          if [[ $fail -eq 1 ]]; then
            echo "Missing .sh/.meta file pairs!"
            exit 1
          fi

          echo "All .sh/.meta file pairs are present."