name: CI for src and tools

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tools/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run 30_* and 40_* tools in order
        run: |
          shopt -s nullglob
          status=0
          for tool in tools/30_*.sh tools/40_*.sh; do
            echo "=== Running: $tool ==="
            bash "$tool"
            result=$?
            if [[ $result -eq 0 ]]; then
              echo "::notice ::PASS: $tool"
            else
              echo "::error ::FAIL: $tool (exit code $result)"
              status=1
            fi
            echo
          done
          shopt -u nullglob
          exit $status
