name: 03 Staging Gate

on:
  pull_request:
    paths:
      - 'staging/**'
      - 'tools/**'

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run numbered tools in order
        run: |
          shopt -s nullglob
          status=0
          for tool in tools/[0-9][0-9]_*.sh; do
            echo "=== Running: $tool ==="
            bash "$tool"
            result=$?
            if [[ $result -eq 0 ]]; then
              echo "::notice ::PASS: $tool"
            else
              echo "::error ::FAIL: $tool (exit code $result)"
              status=1
            fi
            echo
          done
          shopt -u nullglob
          exit $status
